source "https://rubygems.org"
ruby "3.4.3"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem "rails", github: "rails/rails"
gem "rails", "~> 8.0.2"
# Use postgresql as the database for Active Record
gem "propshaft"
gem "pg", "~> 1.1"
# Use Puma as the app server
gem "puma", ">= 5.0"
# Use SCSS for stylesheets
gem "dartsass-rails"
# Use Uglifier as compressor for JavaScript assets
gem "uglifier", ">= 1.3.0"
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem "therubyracer", platforms: :ruby

# Use CoffeeScript for .coffee assets and views
gem "coffee-rails", "~> 4.2"
gem "turbo-rails"
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem "jbuilder"
# Use Redis adapter to run Action Cable in production
gem "redis", ">= 4.0.1"
# Use ActiveModel has_secure_password
# gem "bcrypt", "~> 3.1.7"
gem "httparty"
gem "redcarpet"
gem "mailgun-ruby"
gem "devise"
gem "omniauth"
gem "MailchimpMarketing", "~> 3.0.70"
gem "aws-sdk-s3", require: false
gem "image_processing", "~> 1.2"
gem "importmap-rails"
gem "stimulus-rails"
gem "mini_portile2", "~> 2.8"
gem "rack-brotli"
gem "actionpack-page_caching"
gem "active_model_serializers"
gem "bootsnap", require: false
gem "thruster", require: false
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

# Use Capistrano for deployment
# gem "capistrano-rails", group: :development

group :development, :test do
  # Call "byebug" anywhere in the code to stop execution and get a debugger console
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "capybara"
  gem "selenium-webdriver"
  gem "pry", "~> 0.9.9"
  gem "pry-nav"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem "web-console"
  gem "error_highlight", ">= 0.4.0", platforms: [:ruby]
  gem "listen", ">= 3.0.5", "< 3.2"
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false
end

group :test do
  gem "capybara-screenshot"
  gem "database_cleaner-active_record"
  gem "rails-controller-testing"
  gem "webmock"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:windows, :jruby]
