# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: grubdaily_gourmet_development

test:
  <<: *default
  database: grubdaily_gourmet_test

production:
  <<: *default
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: db-postgresql-lon1-36753-do-user-7372705-0.b.db.ondigitalocean.com
  port: 25060
  username: grubdaily
  database: grubdaily
